try:
    result = 45/2
    print(result)
except:
    print('error happened')
finally:
    print('Done')
    
print('out of try/except')